Changes to batch-cmp

diff --git a/tracediff/examples/batch-cmp b/tracediff/examples/batch-cmp
--- a/tracediff/examples/batch-cmp
+++ b/tracediff/examples/batch-cmp
@@ -1,5 +1,15 @@
 #!/bin/bash
 
+
+if [[ -z $DOOP_HOME ]]; then
+    export DOOP_HOME=`dirname $( readlink -f $( which doop ) )`
+fi
+
+if ! hash doop 2>/dev/null; then
+    echo "error: doop command is not available" >&2
+    exit 1
+fi
+
 set -e # Exit immediately if a command exits with a nonzero exit status
 set -u # Treat unset variables as an error
 export LC_ALL=en_US.UTF-8
@@ -21,15 +31,26 @@ while read settings; do
 
         workspace="analyses/${benchmark}/${benchmark}${suffix}"
         trace="traces/$benchmark-large.gxl"
-        diff="${workspace/analyses/diffs}"
-        jars=`echo $HOME/doop/jars/dacapo/$benchmark*.jar`
+        diff="${workspace/analyses/diffs}.txt"
+        log="${benchmark}${suffix}.log"
+        jars=`echo $DOOP_HOME/jars/dacapo/$benchmark*.jar`
 
         echo "Running benchmark ${benchmark} (stored into $workspace)"
-        doop $settings context-insensitive $HOME/doop/jars/dacapo/$benchmark.jar
-        mkdir -p $(dirname "$workspace")
-        ln -s `readlink -f ~/doop/last-analysis` "$workspace"
-        mkdir -p $(dirname "$diff")
-        ../tracediff.py "$workspace" "$trace" -cp "${jars// /:}" -a2a -a2l -l2a > "$diff"
+
+        set +e
+        doop $settings context-insensitive $DOOP_HOME/jars/dacapo/$benchmark.jar | tee $log
+        set -e
+
+        # Check exit status
+        if [[ $? != 0 ]]; then
+            echo "Benchmark ${benchmark} timed out for $settings" >&2
+            continue
+        fi
+
+        mkdir -p $(dirname $workspace)
+        ln -s `readlink -f $DOOP_HOME/last-analysis` $workspace
+        mkdir -p $(dirname $diff)
+        ../tracediff.py $workspace $trace -cp "${jars// /:}" -a2a -a2l -l2a > $diff
     done
 done <<'EOF'
 
